#ifndef QTSECRET_GLOBAL_H
#define QTSECRET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(Qt_SECRET_LIBRARY)
#  define UNTITLED9SHARED_EXPORT Q_DECL_EXPORT
#else
#  define UNTITLED9SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTSECRET_GLOBAL_H
